import type { CharacterDef } from '../types'

// ponytail: пиксель-арт как символьные карты → SVG-ректы; PNG-спрайты — при полировке
export const PALETTE: Record<string, string> = {
  k: '#1a1523',
  w: '#f4f0e8',
  s: '#e8b48c',
  r: '#d43d3d',
  R: '#8f2323',
  g: '#5cb85c',
  G: '#2e6b34',
  b: '#4a90d9',
  B: '#2a5286',
  y: '#e8c840',
  p: '#9b59b6',
  P: '#5e2f73',
  n: '#8b5a2b',
  l: '#b0b8c4',
  m: '#6b7280',
  o: '#d97b29',
}

export const CHARACTERS: CharacterDef[] = [
  {
    id: 'gnome_devops',
    name: { ru: 'Гном-девопс', en: 'Dwarf devops', es: 'Enano devops', zh: '矮人运维', pt: 'Anão devops' },
    sprite: [
      '.....rr.....',
      '....rrrr....',
      '...rrrrrr...',
      '..rrrrrrrr..',
      '..ssssssss..',
      '..skssssks..',
      '..ssssssss..',
      '.wwwwwwwwww.',
      '.wwwwwwwwww.',
      '..wwwwwwww..',
      '..bbbbbbbb..',
      '..bb....bb..',
    ],
  },
  {
    id: 'elf_designer',
    name: { ru: 'Эльфийка-дизайнер', en: 'Elf designer', es: 'Elfa diseñadora', zh: '精灵设计师', pt: 'Elfa designer' },
    sprite: [
      '....gggg....',
      '...gggggg...',
      '..gggggggg..',
      '.g.ssssss.g.',
      'sg.skssks.gs',
      '.g.ssssss.g.',
      '...ssssss...',
      '...pppppp...',
      '..pppppppp..',
      '..pppppppp..',
      '...pppppp...',
      '...pp..pp...',
    ],
  },
  {
    id: 'dragon_investor',
    name: { ru: 'Дракон-инвестор', en: 'Dragon investor', es: 'Dragón inversor', zh: '投资人巨龙', pt: 'Dragão investidor' },
    sprite: [
      '..G......G..',
      '..GG....GG..',
      '...gggggg...',
      '..gggggggg..',
      '.ggkggggkgg.',
      '.gggggggggg.',
      '..gggggggg..',
      '...gyyyyg...',
      '..kkkkkkkk..',
      '..kkkyykkk..',
      '..kkkkkkkk..',
      '..kk....kk..',
    ],
  },
  {
    id: 'goblin_hater',
    name: { ru: 'Гоблин-хейтер', en: 'Goblin hater', es: 'Goblin hater', zh: '黑粉哥布林', pt: 'Goblin hater' },
    sprite: [
      '..g......g..',
      '.gg......gg.',
      '.gggggggggg.',
      '.gggggggggg.',
      '.ggkggggkgg.',
      '.gggggggggg.',
      '..gRRRRRRg..',
      '...gggggg...',
      '...GGGGGG...',
      '..GGGGGGGG..',
      '..GG....GG..',
      '............',
    ],
  },
  {
    id: 'churn_demon',
    name: { ru: 'Churn-демон', en: 'Churn demon', es: 'Demonio del churn', zh: 'Churn 恶魔', pt: 'Demônio do churn' },
    sprite: [
      '.P........P.',
      '.PP......PP.',
      '..PPppppPP..',
      '..pppppppp..',
      '.ppwppppwpp.',
      '.pppppppppp.',
      '..ppRRRRpp..',
      '..pppppppp..',
      '...pppppp...',
      '...pp..pp...',
      '..pp....pp..',
      '............',
    ],
  },
  {
    id: 'oracle_analyst',
    name: { ru: 'Оракул-аналитик', en: 'Oracle analyst', es: 'Oráculo analista', zh: '神谕分析师', pt: 'Oráculo analista' },
    sprite: [
      '....BBBB....',
      '...BBBBBB...',
      '..BBBBBBBB..',
      '.BBBBBBBBBB.',
      '.BBkyyyykBB.',
      '.BBBBBBBBBB.',
      '..BBBBBBBB..',
      '..BBBBBBBB..',
      '...BBBBBB...',
      '...BBBBBB...',
      '..bb.BB.bb..',
      '............',
    ],
  },
  {
    id: 'support_goblin',
    name: { ru: 'Саппорт-гоблин', en: 'Support goblin', es: 'Goblin de soporte', zh: '客服哥布林', pt: 'Goblin de suporte' },
    sprite: [
      '..mmmmmmmm..',
      '.mggggggggm.',
      '.mggggggggm.',
      '.ggkggggkgg.',
      '.gggggggggg.',
      '..gggwwggg..',
      '...gggggg...',
      '..mbbbbbb...',
      '...bbbbbb...',
      '...bb..bb...',
      '............',
      '............',
    ],
  },
  {
    id: 'lich_competitor',
    name: { ru: 'Лич-конкурент', en: 'Lich competitor', es: 'Liche competidor', zh: '巫妖竞争者', pt: 'Lich concorrente' },
    sprite: [
      '..y..y..y...',
      '..yyyyyyy...',
      '..wwwwwwww..',
      '.wwwwwwwwww.',
      '.wwkwwwwkww.',
      '.wwwwwwwwww.',
      '..ww.ww.ww..',
      '...PPPPPP...',
      '..PPPPPPPP..',
      '..PPPPPPPP..',
      '..PP....PP..',
      '............',
    ],
  },
  {
    id: 'tax_owl',
    name: { ru: 'Налоговая сова', en: 'Tax owl', es: 'Búho fiscal', zh: '税务猫头鹰', pt: 'Coruja fiscal' },
    sprite: [
      '.nn......nn.',
      '.nnnnnnnnnn.',
      '.nwwwnnwwwn.',
      '.nwkwnnwkwn.',
      '.nwwwnnwwwn.',
      '.nnnnyynnnn.',
      '.nnnnnnnnnn.',
      '..nnnnnnnn..',
      '..nnnnnnnn..',
      '...nn..nn...',
      '............',
      '............',
    ],
  },
  {
    id: 'paladin_fan',
    name: { ru: 'Фанат-паладин', en: 'Paladin fan', es: 'Paladín fan', zh: '铁粉圣骑士', pt: 'Paladino fã' },
    sprite: [
      '....yyyy....',
      '...llllll...',
      '..llllllll..',
      '.llllllllll.',
      '.llssssssll.',
      '.llskssksll.',
      '..llllllll..',
      '...ylllly...',
      '..llllllll..',
      '..ll....ll..',
      '............',
      '............',
    ],
  },
]

export const charById = (id: string) => CHARACTERS.find((c) => c.id === id)

// пиксель-портреты билдов основателя
export const FOUNDERS: Record<string, string[]> = {
  coder: [
    '...bbbbbb...',
    '..bbbbbbbb..',
    '.bbssssssbb.',
    '.bskksskksb.',
    '.bssssssssb.',
    '.bssskksssb.',
    '..bssssssb..',
    '..bbbbbbbb..',
    '.bbbbbbbbbb.',
    '.bbkkkkkkbb.',
    '..bb....bb..',
    '............',
  ],
  marketer: [
    '...oooooo...',
    '..oooooooo..',
    '..ssssssss..',
    '..skssssks..',
    '..ssssssss..',
    '..sskkksss..',
    '..rrrrrrrr..',
    '.rrrrrrrrrr.',
    '.rryyyyyyrr.',
    '..rr....rr..',
    '............',
    '............',
  ],
  generalist: [
    '...nnnnnn...',
    '..nnnnnnnn..',
    '..ssssssss..',
    '..skssssks..',
    '..ssssssss..',
    '..ssskksss..',
    '..gggggggg..',
    '.gggggggggg.',
    '.ggnnnnnngg.',
    '..gg....gg..',
    '............',
    '............',
  ],
  excorp: [
    '...mmmmmm...',
    '..mmmmmmmm..',
    '..ssssssss..',
    '..skssssks..',
    '..ssssssss..',
    '..ssskksss..',
    '..kkkwwkkk..',
    '.kkwwrrwwkk.',
    '.kkwwrrwwkk.',
    '..kk....kk..',
    '............',
    '............',
  ],
}
