import type { EventDef } from '../types'

// 52 события. Вес по стадиям; requires отсекают бессмысленные (нет прода — не падает прод)
export const EVENTS: EventDef[] = [
  // ── РЫНОК ────────────────────────────────────────────────
  {
    id: 'lich_copied',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Лич скопировал твою фичу', en: 'The lich copied your feature', es: 'El liche copió tu feature', zh: '巫妖抄了你的功能', pt: 'O lich copiou sua feature' },
    text: { ru: '«Некроманты не изобретают. Некроманты поднимают чужое», — пишет он в чейнджлоге.', en: '"Necromancers don\'t invent. Necromancers raise what\'s dead," says his changelog.', es: '«Los nigromantes no inventan. Los nigromantes levantan lo ajeno», dice su changelog.', zh: '"死灵法师从不发明。死灵法师只复活别人的东西。"他在更新日志里写道。', pt: '"Necromantes não inventam. Necromantes ressuscitam o que é dos outros", diz o changelog dele.' },
    fx: { traffic: { mult: 0.7, days: 5 }, motivation: -3 },
  },
  {
    id: 'niche_hype',
    cat: 'market', char: 'oracle_analyst',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Ниша хайпанула', en: 'Your niche is hyped', es: 'Tu nicho se puso de moda', zh: '你的赛道火了', pt: 'Seu nicho bombou' },
    text: { ru: 'Кто-то крупный написал тред «будущее за этим». Спрос ×2 на неделю.', en: 'Someone big tweeted "this is the future". Demand ×2 for a week.', es: 'Alguien grande tuiteó «esto es el futuro». Demanda ×2 durante una semana.', zh: '某位大V发帖说"未来属于这个方向"。需求 ×2,持续一周。', pt: 'Alguém grande tuitou "isso é o futuro". Demanda ×2 por uma semana.' },
    fx: { demand: { mult: 2, days: 7 } },
  },
  {
    id: 'donor_price_up',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.donorResearched,
    title: { ru: 'Донор поднял цены', en: 'Your donor raised prices', es: 'Tu donante subió los precios', zh: '你的"供体"涨价了', pt: 'Seu doador subiu os preços' },
    text: { ru: 'Конкурент-донор поднял цены ×2. Его юзеры смотрят по сторонам. Например, на тебя.', en: 'The donor competitor doubled prices. Their users are looking around. At you, for example.', es: 'El competidor donante duplicó los precios. Sus usuarios están mirando alrededor. A ti, por ejemplo.', zh: '那个"供体"竞品把价格翻了一倍。他们的用户开始东张西望。比如,望向你。', pt: 'O concorrente doador dobrou os preços. Os usuários dele estão olhando ao redor. Para você, por exemplo.' },
    fx: { pmfBonus: 0.03 },
  },
  {
    id: 'competitor_died',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Конкурент закрылся', en: 'A competitor shut down', es: 'Un competidor cerró', zh: '一个竞品倒闭了', pt: 'Um concorrente fechou as portas' },
    text: { ru: '«Спасибо за путешествие» — пост на их лендинге. Их трафик ищет новый дом.', en: '"Thanks for the journey" — says their landing page. Their traffic seeks a new home.', es: '«Gracias por el viaje» — dice su landing. Su tráfico busca un nuevo hogar.', zh: '"感谢一路相伴"——他们的落地页如是说。他们的流量正在寻找新家。', pt: '"Obrigado pela jornada" — diz a landing deles. O tráfego deles procura um novo lar.' },
    fx: { traffic: { mult: 1.4, days: 5 } },
  },
  {
    id: 'market_cooldown',
    cat: 'market', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    title: { ru: 'Рынок остыл', en: 'The market cooled off', es: 'El mercado se enfrió', zh: '市场降温了', pt: 'O mercado esfriou' },
    text: { ru: 'Хайп ушёл в соседнюю нишу. Спрос −40% на несколько дней.', en: 'The hype moved next door. Demand −40% for a few days.', es: 'El hype se mudó al nicho de al lado. Demanda −40% por unos días.', zh: '热度转移到了隔壁赛道。需求 −40%,持续几天。', pt: 'O hype se mudou para o nicho ao lado. Demanda −40% por alguns dias.' },
    fx: { demand: { mult: 0.6, days: 5 } },
  },
  {
    id: 'lich_launch_day',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Лич лончится в твой день', en: 'The lich launches on your day', es: 'El liche lanza el mismo día que tú', zh: '巫妖和你同一天发布', pt: 'O lich lança no seu dia' },
    text: { ru: 'Он вышел на Product Cave с «AI-powered» версией твоего продукта. Внимание рынка — не твоё.', en: 'He hit Product Cave with an "AI-powered" version of your product. The market\'s attention is not yours.', es: 'Salió en Product Cave con una versión «AI-powered» de tu producto. La atención del mercado no es tuya.', zh: '他带着你产品的"AI-powered"版本登上了 Product Cave。市场的注意力不属于你。', pt: 'Ele chegou ao Product Cave com uma versão "AI-powered" do seu produto. A atenção do mercado não é sua.' },
    fx: { traffic: { mult: 0.6, days: 3 } },
  },
  {
    id: 'copycat_you',
    cat: 'market', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Тебя склонировали за выходные', en: 'You got cloned over a weekend', es: 'Te clonaron en un fin de semana', zh: '一个周末你就被克隆了', pt: 'Clonaram você em um fim de semana' },
    text: { ru: 'Некий студент собрал клон «за 2 вечера» и написал об этом тред.', en: 'Some student built a clone "in 2 evenings" and wrote a thread about it.', es: 'Un estudiante montó un clon «en 2 tardes» y escribió un hilo al respecto.', zh: '某个学生"花 2 个晚上"搓了个克隆版,还发帖讲了这事。', pt: 'Um estudante montou um clone "em 2 noites" e escreveu uma thread sobre isso.' },
    choices: [
      { label: { ru: 'Написать разбор, почему твой лучше (−2⚡)', en: 'Write a breakdown why yours is better (−2⚡)', es: 'Escribir un análisis de por qué el tuyo es mejor (−2⚡)', zh: '写篇分析,说明你的更好(−2⚡)', pt: 'Escrever uma análise de por que o seu é melhor (−2⚡)' }, fx: { energy: -2, audience: 100 } },
      { label: { ru: 'Игнорировать', en: 'Ignore', es: 'Ignorar', zh: '无视', pt: 'Ignorar' }, fx: { motivation: -4 } },
    ],
  },
  // ── ТЕХНИЧЕСКИЕ ──────────────────────────────────────────
  {
    id: 'prod_down_friday',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.deployed,
    title: { ru: 'Прод упал. Пятница, 23:40', en: 'Prod is down. Friday, 11:40pm', es: 'Producción caída. Viernes, 23:40', zh: '生产环境挂了。周五,23:40', pt: 'Produção fora do ar. Sexta, 23:40' },
    text: { ru: 'Гном-девопс уже здесь. Требует пива и $200. Или чини сам.', en: 'The dwarf devops is here. Demands beer and $200. Or fix it yourself.', es: 'El enano devops ya está aquí. Exige cerveza y $200. O arréglalo tú mismo.', zh: '矮人运维已经到场。要啤酒,还要 $200。不然就自己修。', pt: 'O anão devops já está aqui. Exige cerveja e $200. Ou conserte você mesmo.' },
    choices: [
      { label: { ru: 'Чинить ночью самому', en: 'Fix it overnight yourself', es: 'Arreglarlo tú mismo esta noche', zh: '连夜自己修', pt: 'Consertar você mesmo de madrugada' }, fx: { energy: -4, motivation: -5 } },
      { label: { ru: 'Заплатить гному $200', en: 'Pay the dwarf $200', es: 'Pagarle $200 al enano', zh: '付给矮人 $200', pt: 'Pagar $200 ao anão' }, fx: { money: -200 } },
      { label: { ru: 'Забить до понедельника', en: 'Ignore until Monday', es: 'Ignorar hasta el lunes', zh: '拖到周一再说', pt: 'Deixar para segunda-feira' }, fx: {}, risk: { prob: 0.5, fx: { churnPct: 0.2, motivation: -4 }, label: { ru: 'Юзеры заметили. Churn-демон доволен', en: 'Users noticed. The churn demon is pleased', es: 'Los usuarios se dieron cuenta. El demonio del churn está satisfecho', zh: '用户发现了。churn 恶魔很满意', pt: 'Os usuários perceberam. O demônio do churn está satisfeito' } } },
    ],
  },
  {
    id: 'wyvercel_pricing',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Wyvercel сменил тарифы', en: 'Wyvercel changed pricing', es: 'Wyvercel cambió sus tarifas', zh: 'Wyvercel 改了定价', pt: 'A Wyvercel mudou os preços' },
    text: { ru: '«Мы упрощаем тарифы» = теперь дороже. Классика.', en: '"We are simplifying pricing" = it\'s more expensive now. A classic.', es: '«Estamos simplificando las tarifas» = ahora es más caro. Un clásico.', zh: '"我们正在简化定价" = 现在更贵了。经典操作。', pt: '"Estamos simplificando os preços" = agora está mais caro. Um clássico.' },
    fx: { infra: 30 },
  },
  {
    id: 'critical_bug_client',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Критический баг у крупного клиента', en: 'Critical bug at a big client', es: 'Bug crítico en un cliente grande', zh: '大客户遇到严重 bug', pt: 'Bug crítico em um cliente grande' },
    text: { ru: 'Скриншот в саппорт, три восклицательных знака, слово «СРОЧНО» капсом.', en: 'A screenshot in support, three exclamation marks, the word "URGENT" in caps.', es: 'Una captura en soporte, tres signos de exclamación, la palabra «URGENTE» en mayúsculas.', zh: '客服里一张截图,三个感叹号,"紧急"两个字放得老大。', pt: 'Um print no suporte, três pontos de exclamação, a palavra "URGENTE" em caixa alta.' },
    choices: [
      { label: { ru: 'Чинить ночью (−мотивация)', en: 'Fix overnight (−motivation)', es: 'Arreglarlo de madrugada (−motivación)', zh: '连夜修复(−动力)', pt: 'Consertar de madrugada (−motivação)' }, fx: { motivation: -6, bugs: -2 } },
      { label: { ru: 'Забить', en: 'Ignore', es: 'Ignorar', zh: '无视', pt: 'Ignorar' }, fx: {}, risk: { prob: 0.7, fx: { churnPct: 0.12 }, label: { ru: 'Клиент ушёл и увёл друзей', en: 'The client left and took friends along', es: 'El cliente se fue y se llevó a sus amigos', zh: '客户走了,还带走了朋友', pt: 'O cliente foi embora e levou os amigos junto' } } },
    ],
  },
  {
    id: 'ddos_goblins',
    cat: 'tech', char: 'goblin_hater',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Гоблины дудосят', en: 'Goblins are DDoSing you', es: 'Los goblins te están haciendo DDoS', zh: '哥布林正在 DDoS 你', pt: 'Os goblins estão fazendo DDoS em você' },
    text: { ru: 'Кто-то из Dungeon Boards обиделся на твой пост. Сайт лежит.', en: 'Someone from Dungeon Boards got offended by your post. The site is down.', es: 'Alguien de Dungeon Boards se ofendió por tu post. El sitio está caído.', zh: 'Dungeon Boards 上有人被你的帖子惹恼了。网站挂了。', pt: 'Alguém do Dungeon Boards se ofendeu com seu post. O site está fora do ar.' },
    choices: [
      { label: { ru: 'Оплатить щит CDN ($150)', en: 'Pay for a CDN shield ($150)', es: 'Pagar un escudo CDN ($150)', zh: '买个 CDN 护盾($150)', pt: 'Pagar um escudo de CDN ($150)' }, fx: { money: -150 } },
      { label: { ru: 'Переждать', en: 'Wait it out', es: 'Esperar a que pase', zh: '硬扛过去', pt: 'Esperar passar' }, fx: { traffic: { mult: 0.5, days: 2 } } },
    ],
  },
  {
    id: 'data_loss',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Потерял кусок данных', en: 'You lost some data', es: 'Perdiste parte de los datos', zh: '你丢了一块数据', pt: 'Você perdeu parte dos dados' },
    text: { ru: 'Бекапы? Какие бекапы. Ты же соло-фаундер, у тебя нет времени на бекапы.', en: 'Backups? What backups. You\'re a solo founder, no time for backups.', es: '¿Backups? Qué backups. Eres un fundador en solitario, no tienes tiempo para backups.', zh: '备份?什么备份。你可是单人创始人,哪有时间做备份。', pt: 'Backups? Que backups. Você é um fundador solo, não tem tempo para backups.' },
    fx: { bugs: 2, motivation: -4 },
  },
  {
    id: 'api_deprecated',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.progress >= 40,
    title: { ru: 'Ключевая зависимость всё', en: 'A key dependency is dead', es: 'Una dependencia clave murió', zh: '关键依赖凉了', pt: 'Uma dependência-chave morreu' },
    text: { ru: 'Библиотека, на которой всё держится, помечена deprecated. Мейнтейнер ушёл разводить овец.', en: 'The library holding everything together is deprecated. The maintainer left to herd sheep.', es: 'La librería que lo sostiene todo está deprecated. El mantenedor se fue a criar ovejas.', zh: '撑起整个项目的那个库被标成了 deprecated。维护者跑去养羊了。', pt: 'A biblioteca que segura tudo foi marcada como deprecated. O mantenedor foi criar ovelhas.' },
    choices: [
      { label: { ru: 'День на миграцию (−6⚡)', en: 'A day of migration (−6⚡)', es: 'Un día de migración (−6⚡)', zh: '花一天迁移(−6⚡)', pt: 'Um dia de migração (−6⚡)' }, fx: { energy: -6 } },
      { label: { ru: 'Работает — не трогай', en: "If it works, don't touch it", es: 'Si funciona, no lo toques', zh: '能跑就别动', pt: 'Se funciona, não mexe' }, fx: { bugs: 3 } },
    ],
  },
  {
    id: 'wyvercel_grant',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 2, traction: 1 },
    requires: (s) => s.deployed,
    title: { ru: 'Wyvercel дал кредиты', en: 'Wyvercel gave you credits', es: 'Wyvercel te dio créditos', zh: 'Wyvercel 送了你额度', pt: 'A Wyvercel te deu créditos' },
    text: { ru: 'Программа поддержки инди-магов: $100 кредитов на инфру. Мелочь, а приятно.', en: 'Indie mage support program: $100 in infra credits. Small, but nice.', es: 'Programa de apoyo a magos indie: $100 en créditos de infra. Poca cosa, pero se agradece.', zh: '独立法师扶持计划:$100 基础设施额度。不多,但暖心。', pt: 'Programa de apoio a magos indie: $100 em créditos de infra. Pouco, mas conta.' },
    fx: { money: 100 },
  },
  {
    id: 'gnome_cache_tip',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Гном посоветовал кеш', en: 'The dwarf suggested caching', es: 'El enano sugirió usar caché', zh: '矮人建议加缓存', pt: 'O anão sugeriu usar cache' },
    text: { ru: '«Поставь кеш, балда» — сказал гном. Инфра подешевела.', en: '"Add a cache, you dolt," said the dwarf. Infra got cheaper.', es: '«Ponle un caché, zoquete», dijo el enano. La infra salió más barata.', zh: '"加个缓存啊,笨蛋。"矮人说。基础设施费用降了。', pt: '"Bota um cache, jumento", disse o anão. A infra ficou mais barata.' },
    fx: { infra: -10 },
  },
  // ── СОЦСЕТИ / ЛОНЧ ───────────────────────────────────────
  {
    id: 'post_viral',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.audience >= 20,
    title: { ru: 'Пост завирусился', en: 'Your post went viral', es: 'Tu post se hizo viral', zh: '你的帖子爆了', pt: 'Seu post viralizou' },
    text: { ru: 'Алгоритм Xitter сегодня на твоей стороне. Аудитория ×3.', en: 'The Xitter algorithm is on your side today. Audience ×3.', es: 'El algoritmo de Xitter hoy está de tu lado. Audiencia ×3.', zh: '今天 Xitter 的算法站在你这边。粉丝 ×3。', pt: 'O algoritmo do Xitter está do seu lado hoje. Audiência ×3.' },
    fx: { audienceMult: 3 },
  },
  {
    id: 'goblin_comments',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.audience >= 10,
    title: { ru: 'Гоблины в комментах', en: 'Goblins in the comments', es: 'Goblins en los comentarios', zh: '评论区来了哥布林', pt: 'Goblins nos comentários' },
    text: { ru: '«поделка», «такое уже есть», «а почему не опенсорс?»', en: '"toy project", "this already exists", "why isn\'t it open source?"', es: '«un juguetito», «esto ya existe», «¿por qué no es open source?»', zh: '"玩具项目""这早就有了""为什么不开源?"', pt: '"projetinho de brinquedo", "isso já existe", "por que não é open source?"' },
    choices: [
      { label: { ru: 'Отвечать каждому (−2⚡)', en: 'Reply to each one (−2⚡)', es: 'Responder a cada uno (−2⚡)', zh: '挨个回复(−2⚡)', pt: 'Responder um por um (−2⚡)' }, fx: { energy: -2 }, risk: { prob: 0.4, fx: { motivation: -5 }, label: { ru: 'Затянуло в срач на 3 часа', en: 'Got dragged into a 3-hour flame war', es: 'Te arrastraron a una pelea de 3 horas', zh: '被拖进了 3 小时的骂战', pt: 'Foi arrastado para uma treta de 3 horas' } } },
      { label: { ru: 'Игнорировать', en: 'Ignore', es: 'Ignorar', zh: '无视', pt: 'Ignorar' }, fx: { motivation: -3 } },
    ],
  },
  {
    id: 'product_cave_feature',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Фичеринг на Product Cave', en: 'Featured on Product Cave', es: 'Destacado en Product Cave', zh: '登上 Product Cave 精选', pt: 'Destaque no Product Cave' },
    text: { ru: 'Редакция пещеры выбрала тебя продуктом недели. Трафик ×3.', en: 'The cave editors picked you as product of the week. Traffic ×3.', es: 'Los editores de la cueva te eligieron producto de la semana. Tráfico ×3.', zh: '洞穴编辑部选你为本周产品。流量 ×3。', pt: 'Os editores da caverna te escolheram produto da semana. Tráfego ×3.' },
    fx: { traffic: { mult: 3, days: 2 } },
  },
  {
    id: 'big_account_shitpost',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Шитпост про тебя от крупного аккаунта', en: 'A big account shitposted about you', es: 'Una cuenta grande hizo un shitpost sobre ti', zh: '大V发帖嘲讽你', pt: 'Uma conta grande fez shitpost sobre você' },
    text: { ru: '«Индихакеры опять изобрели то, что было в 2009». 2 миллиона просмотров.', en: '"Indie hackers reinvented something from 2009 again." 2 million views.', es: '«Los indie hackers volvieron a inventar algo que ya existía en 2009». 2 millones de vistas.', zh: '"独立开发者又发明了一个 2009 年就有的东西。"200 万浏览量。', pt: '"Os indie hackers reinventaram de novo algo de 2009." 2 milhões de visualizações.' },
    fx: { motivation: -6, audience: 80 },
  },
  {
    id: 'algo_change',
    cat: 'social', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.channels.social > 0.5,
    title: { ru: 'Xitter поменял алгоритм', en: 'Xitter changed the algorithm', es: 'Xitter cambió el algoritmo', zh: 'Xitter 改了算法', pt: 'O Xitter mudou o algoritmo' },
    text: { ru: 'Теперь показывают только видео с котами. У тебя SaaS. Не с котами.', en: 'Now it only shows cat videos. You have a SaaS. Without cats.', es: 'Ahora solo muestra vídeos de gatos. Tú tienes un SaaS. Sin gatos.', zh: '现在只推猫咪视频。你做的是 SaaS。没有猫。', pt: 'Agora só mostra vídeo de gato. Você tem um SaaS. Sem gatos.' },
    fx: { traffic: { mult: 0.7, days: 4 } },
  },
  {
    id: 'dm_collab',
    cat: 'social', char: 'elf_designer',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.audience >= 50,
    title: { ru: 'Микроинфлюенсер предлагает коллаб', en: 'A micro-influencer offers a collab', es: 'Un microinfluencer propone una colab', zh: '小网红来谈合作', pt: 'Um microinfluenciador propõe uma collab' },
    text: { ru: '«Сделаю обзор за $150. У меня очень вовлечённая аудитория (мама и два гнома)».', en: '"I\'ll review it for $150. My audience is super engaged (my mom and two dwarves)."', es: '«Hago una reseña por $150. Mi audiencia es súper fiel (mi madre y dos enanos)».', zh: '"给我 $150 就做测评。我的粉丝黏性超高(我妈和两个矮人)。"', pt: '"Faço uma resenha por $150. Minha audiência é superengajada (minha mãe e dois anões)."' },
    choices: [
      { label: { ru: 'Заплатить $150', en: 'Pay $150', es: 'Pagar $150', zh: '付 $150', pt: 'Pagar $150' }, fx: { money: -150, audience: 200 } },
      { label: { ru: 'Вежливо отказаться', en: 'Politely decline', es: 'Rechazar amablemente', zh: '礼貌拒绝', pt: 'Recusar educadamente' }, fx: {} },
    ],
  },
  {
    id: 'paladin_thread',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: 'Фанат-паладин написал тред', en: 'The paladin fan wrote a thread', es: 'El paladín fan escribió un hilo', zh: '圣骑士粉丝发了个长帖', pt: 'O paladino fã escreveu uma thread' },
    text: { ru: '«Этот продукт изменил мой воркфлоу» — 12 твитов, все с эмодзи меча.', en: '"This product changed my workflow" — 12 tweets, all with sword emojis.', es: '«Este producto cambió mi flujo de trabajo» — 12 tuits, todos con emojis de espada.', zh: '"这个产品改变了我的工作流"——12 条推文,每条都带宝剑表情。', pt: '"Esse produto mudou meu workflow" — 12 tweets, todos com emoji de espada.' },
    fx: { motivation: 6, audience: 60 },
  },
  {
    id: 'hn_frontpage',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Фронтпейдж Dungeon News', en: 'Dungeon News front page', es: 'Portada de Dungeon News', zh: '登上 Dungeon News 首页', pt: 'Primeira página do Dungeon News' },
    text: { ru: 'Трафик ×4. В комментах спорят о лицензии и почему ты не сделал это на Lisp.', en: 'Traffic ×4. The comments argue about your license and why you didn\'t use Lisp.', es: 'Tráfico ×4. En los comentarios discuten tu licencia y por qué no lo hiciste en Lisp.', zh: '流量 ×4。评论区在争论你的开源协议,以及你为什么不用 Lisp 写。', pt: 'Tráfego ×4. Nos comentários discutem sua licença e por que você não fez isso em Lisp.' },
    fx: { traffic: { mult: 4, days: 1 }, motivation: -2 },
  },
  {
    id: 'seo_update',
    cat: 'social', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.channels.seo > 1,
    title: { ru: 'Кор-апдейт поисковика', en: 'Search engine core update', es: 'Core update del buscador', zh: '搜索引擎核心算法更新', pt: 'Core update do buscador' },
    text: { ru: 'Google перетасовал выдачу. Твои позиции просели «временно» (никто не знает, насколько).', en: 'Google reshuffled the results. Your rankings dipped "temporarily" (nobody knows for how long).', es: 'Google barajó los resultados. Tus posiciones cayeron «temporalmente» (nadie sabe por cuánto).', zh: 'Google 重排了搜索结果。你的排名"暂时"下滑了(没人知道要多久)。', pt: 'O Google embaralhou os resultados. Suas posições caíram "temporariamente" (ninguém sabe por quanto tempo).' },
    fx: { traffic: { mult: 0.75, days: 7 } },
  },
  {
    id: 'opensource_clone',
    cat: 'social', char: 'lich_competitor',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Появился опенсорс-клон', en: 'An open-source clone appeared', es: 'Apareció un clon open source', zh: '出现了开源克隆版', pt: 'Apareceu um clone open source' },
    text: { ru: '«Как твой продукт, только бесплатно и с багами». 800 звёзд за сутки.', en: '"Like your product, but free and buggy." 800 stars overnight.', es: '«Como tu producto, pero gratis y con bugs». 800 estrellas en una noche.', zh: '"和你的产品一样,但免费,还带 bug。"一天之内 800 颗星。', pt: '"Igual ao seu produto, só que grátis e cheio de bugs." 800 estrelas da noite para o dia.' },
    choices: [
      { label: { ru: 'Паниковать', en: 'Panic', es: 'Entrar en pánico', zh: '陷入恐慌', pt: 'Entrar em pânico' }, fx: { motivation: -4 } },
      { label: { ru: 'Публично похвалить (маркетинг!)', en: 'Publicly praise it (marketing!)', es: 'Elogiarlo en público (¡marketing!)', zh: '公开夸它(这也是营销!)', pt: 'Elogiar em público (marketing!)' }, fx: { audience: 120 } },
    ],
  },
  {
    id: 'podcast_invite',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.audience >= 100,
    title: { ru: 'Позвали на подкаст', en: 'Invited to a podcast', es: 'Te invitaron a un podcast', zh: '播客邀请你做嘉宾', pt: 'Convidaram você para um podcast' },
    text: { ru: '«Гильдия одного: как выжить соло». Два часа разговоров, четыре слушателя, но какие!', en: '"Guild of One: surviving solo." Two hours of talk, four listeners — but what listeners!', es: '«Gremio de uno: cómo sobrevivir en solitario». Dos horas de charla, cuatro oyentes, ¡pero qué oyentes!', zh: '《一个人的公会:单干求生记》。聊了两个小时,四个听众——但个个是精品!', pt: '"Guilda de um: sobrevivendo solo." Duas horas de papo, quatro ouvintes — mas que ouvintes!' },
    choices: [
      { label: { ru: 'Пойти (−4⚡)', en: 'Go (−4⚡)', es: 'Ir (−4⚡)', zh: '去(−4⚡)', pt: 'Ir (−4⚡)' }, fx: { energy: -4, audience: 150, motivation: 3 } },
      { label: { ru: 'Отказаться', en: 'Decline', es: 'Rechazar', zh: '拒绝', pt: 'Recusar' }, fx: {} },
    ],
  },
  {
    id: 'mrr_screenshot_trend',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.mrr > 0,
    title: { ru: 'Тренд «покажи свой MRR»', en: '"Show your MRR" trend', es: 'Tendencia «enseña tu MRR»', zh: '"晒出你的 MRR"成了风潮', pt: 'Trend "mostre seu MRR"' },
    text: { ru: 'Все постят скриншоты дашбордов. Building in public — религия со своими обрядами.', en: 'Everyone posts dashboard screenshots. Building in public is a religion with rituals.', es: 'Todos publican capturas de sus dashboards. Building in public es una religión con sus ritos.', zh: '人人都在晒仪表盘截图。Building in public 是一门有自己仪式的宗教。', pt: 'Todo mundo posta print de dashboard. Building in public é uma religião com seus rituais.' },
    fx: { audience: 120 },
  },
  // ── ЛИЧНЫЕ ───────────────────────────────────────────────
  {
    id: 'cold',
    cat: 'personal', char: 'gnome_devops',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Простуда', en: 'You caught a cold', es: 'Te resfriaste', zh: '感冒了', pt: 'Você pegou um resfriado' },
    text: { ru: 'Горло болит, нос течёт, дедлайны сами себя не сдвинут (сдвинут).', en: 'Sore throat, runny nose. The deadlines won\'t move themselves (they will).', es: 'Dolor de garganta, nariz que gotea. Los deadlines no se moverán solos (sí lo harán).', zh: '嗓子疼,鼻涕流。截止日期不会自己往后挪(其实会)。', pt: 'Garganta doendo, nariz escorrendo. Os prazos não vão se adiar sozinhos (vão sim).' },
    fx: { sick: { energy: -4, days: 3 } },
  },
  {
    id: 'friend_vacation',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Друг зовёт в отпуск', en: 'A friend invites you on vacation', es: 'Un amigo te invita de vacaciones', zh: '朋友喊你去度假', pt: 'Um amigo te chama para férias' },
    text: { ru: '«Ты же сам себе начальник, отпросись у себя». Аргумент железный.', en: '"You\'re your own boss, ask yourself for time off." Solid argument.', es: '«Eres tu propio jefe, pídete permiso a ti mismo». Argumento de hierro.', zh: '"你自己就是老板,跟自己请个假呗。"无法反驳。', pt: '"Você é seu próprio chefe, peça folga para si mesmo." Argumento imbatível.' },
    choices: [
      { label: { ru: 'Поехать (−$500)', en: 'Go (−$500)', es: 'Ir (−$500)', zh: '去(−$500)', pt: 'Ir (−$500)' }, fx: { money: -500, motivation: 15, energy: -10 } },
      { label: { ru: 'Отказаться', en: 'Decline', es: 'Rechazar', zh: '拒绝', pt: 'Recusar' }, fx: { motivation: -6 } },
    ],
  },
  {
    id: 'job_offer',
    cat: 'personal', char: 'dragon_investor',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Оффер из найма', en: 'A job offer', es: 'Una oferta de empleo', zh: '收到工作 offer', pt: 'Uma oferta de emprego' },
    text: { ru: 'Бывший коллега: «У нас открылась позиция, х2 от твоей прошлой зарплаты. Подумай».', en: 'An ex-colleague: "We have an opening, 2x your old salary. Think about it."', es: 'Un excolega: «Tenemos una vacante, 2x tu sueldo anterior. Piénsalo».', zh: '前同事:"我们这边有个空缺,薪水是你之前的 2 倍。考虑一下。"', pt: 'Um ex-colega: "Abriu uma vaga aqui, 2x seu salário antigo. Pensa aí."' },
    choices: [
      { label: { ru: 'Отказаться. Ты выбрал этот путь', en: 'Decline. You chose this path', es: 'Rechazar. Tú elegiste este camino', zh: '拒绝。这条路是你自己选的', pt: 'Recusar. Você escolheu esse caminho' }, fx: { motivation: 4 } },
      { label: { ru: 'Принять оффер (конец рана)', en: 'Accept the offer (run ends)', es: 'Aceptar la oferta (fin de la partida)', zh: '接受 offer(本局结束)', pt: 'Aceitar a oferta (fim da run)' }, fx: { end: 'quit_job' } },
    ],
  },
  {
    id: 'back_pain',
    cat: 'personal', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    title: { ru: 'Спина передаёт привет', en: 'Your back says hi', es: 'Tu espalda te manda saludos', zh: '腰在向你问好', pt: 'Suas costas mandam lembranças' },
    text: { ru: '14 часов за столом из «просто доделаю» превратились в визит к костоправу.', en: '14 hours at the desk of "just finishing up" turned into a chiropractor visit.', es: '14 horas de escritorio de «ya casi termino» acabaron en visita al quiropráctico.', zh: '"马上就收尾"变成了在桌前坐 14 个小时,最后进了正骨师的门。', pt: '14 horas na mesa de "só vou terminar isso" viraram uma visita ao quiroprata.' },
    fx: { sick: { energy: -2, days: 2 }, motivation: -2 },
  },
  {
    id: 'imposter',
    cat: 'personal', char: 'churn_demon',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Синдром самозванца', en: 'Impostor syndrome', es: 'Síndrome del impostor', zh: '冒名顶替综合征', pt: 'Síndrome do impostor' },
    text: { ru: 'Все вокруг делают $30k MRR (в твитах). А ты кто вообще такой?', en: 'Everyone around makes $30k MRR (in tweets). Who even are you?', es: 'Todos a tu alrededor hacen $30k de MRR (en sus tuits). ¿Y tú quién eres?', zh: '身边人人都是 $30k MRR(在推文里)。你算老几?', pt: 'Todo mundo ao redor faz $30k de MRR (nos tweets). E você, quem é?' },
    choices: [
      { label: { ru: 'Сессия у барда-терапевта ($120)', en: 'A session with the bard therapist ($120)', es: 'Sesión con el bardo terapeuta ($120)', zh: '找吟游诗人心理师聊一次($120)', pt: 'Sessão com o bardo terapeuta ($120)' }, fx: { money: -120, motivation: 6 } },
      { label: { ru: 'Перетерпеть', en: 'Push through', es: 'Aguantar', zh: '硬扛', pt: 'Aguentar firme' }, fx: { motivation: -8 } },
    ],
  },
  {
    id: 'old_friend_praise',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Старый друг гордится', en: 'An old friend is proud', es: 'Un viejo amigo está orgulloso', zh: '老朋友为你骄傲', pt: 'Um velho amigo está orgulhoso' },
    text: { ru: '«Слушай, я видел твой проект. Круто, что ты решился». Внезапно приятно.', en: '"Hey, I saw your project. Takes guts, respect." Unexpectedly nice.', es: '«Oye, vi tu proyecto. Qué valiente, en serio». Inesperadamente agradable.', zh: '"哎,我看到你的项目了。敢干,真牛。"意外地暖心。', pt: '"Ei, vi seu projeto. Que coragem, respeito." Inesperadamente bom de ouvir.' },
    fx: { motivation: 8 },
  },
  {
    id: 'insomnia',
    cat: 'personal', char: 'churn_demon',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Бессонница', en: 'Insomnia', es: 'Insomnio', zh: '失眠', pt: 'Insônia' },
    text: { ru: 'До трёх ночи листал чужие истории успеха. Утром — как будто тебя переехал голем.', en: 'Scrolled other people\'s success stories until 3am. Morning feels like a golem ran you over.', es: 'Estuviste hasta las 3 de la mañana leyendo historias de éxito ajenas. Por la mañana, como si te hubiera atropellado un gólem.', zh: '刷别人的成功故事刷到凌晨三点。早上感觉像被魔像碾过一样。', pt: 'Ficou até as 3 da manhã lendo histórias de sucesso dos outros. De manhã, parece que um golem passou por cima de você.' },
    fx: { energy: -3 },
  },
  {
    id: 'motivational_video',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Мотивационный ролик вместо работы', en: 'A motivational video instead of work', es: 'Un vídeo motivacional en vez de trabajar', zh: '没干活,看了个励志视频', pt: 'Um vídeo motivacional em vez de trabalho' },
    text: { ru: '«Как я сделал $1M за год» — 40 минут. Работа не сделана, но настрой боевой.', en: '"How I made $1M in a year" — 40 minutes. No work done, but the spirit is high.', es: '«Cómo hice $1M en un año» — 40 minutos. Trabajo hecho: cero. Ánimo: por las nubes.', zh: '《我如何一年赚到 $1M》——40 分钟。活没干,但斗志昂扬。', pt: '"Como fiz $1M em um ano" — 40 minutos. Trabalho feito: nenhum. Mas o ânimo está lá em cima.' },
    fx: { energy: -1, motivation: 2 },
  },
  // ── ДЕНЬГИ ───────────────────────────────────────────────
  {
    id: 'dragon_invest',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 0, traction: 3 },
    requires: (s) => s.mrr >= 500 && s.investorShare === 0,
    title: { ru: 'Дракон-инвестор предлагает сделку', en: 'The dragon investor offers a deal', es: 'El dragón inversor te ofrece un trato', zh: '巨龙投资人开价了', pt: 'O dragão investidor oferece um acordo' },
    text: { ru: '«$50,000 за 20% твоей пещеры. Драконы плохого не посоветуют. Драконам».', en: '"$50,000 for 20% of your cave. Dragons never give bad advice. To dragons."', es: '«$50,000 por el 20% de tu cueva. Los dragones nunca dan malos consejos. A los dragones».', zh: '"$50,000 换你洞穴的 20%。龙从不出馊主意——对龙自己而言。"', pt: '"$50,000 por 20% da sua caverna. Dragões nunca dão maus conselhos. Para dragões."' },
    choices: [
      { label: { ru: 'Взять $50k (отдать 20% MRR)', en: 'Take $50k (give up 20% of MRR)', es: 'Aceptar los $50k (ceder el 20% del MRR)', zh: '拿下 $50k(让出 20% 的 MRR)', pt: 'Pegar os $50k (abrir mão de 20% do MRR)' }, fx: { money: 50000, share: 0.2 } },
      { label: { ru: 'Отказаться. Bootstrapped и гордый', en: 'Decline. Bootstrapped and proud', es: 'Rechazar. Bootstrapped y orgulloso', zh: '拒绝。Bootstrapped,而且骄傲', pt: 'Recusar. Bootstrapped e orgulhoso' }, fx: { motivation: 3 } },
    ],
  },
  {
    id: 'tax_owl_letter',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.money > 400,
    title: { ru: 'Письмо от налоговой совы', en: 'A letter from the tax owl', es: 'Carta de la lechuza fiscal', zh: '税务猫头鹰来信', pt: 'Uma carta da coruja fiscal' },
    text: { ru: '«Уху. Вы забыли подать форму 27-Б. Уху-ху». Совы не прощают.', en: '"Hoo. You forgot to file form 27-B. Hoo-hoo." Owls do not forgive.', es: '«Uhú. Olvidó presentar el formulario 27-B. Uhú-hú». Las lechuzas no perdonan.', zh: '"咕。你忘了提交 27-B 表格。咕咕。"猫头鹰从不宽恕。', pt: '"Uhu. Você esqueceu de entregar o formulário 27-B. Uhu-hu." Corujas não perdoam.' },
    fx: { money: -300, motivation: -2 },
  },
  {
    id: 'annual_plan',
    cat: 'money', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 2,
    title: { ru: 'Клиент купил годовой план', en: 'A client bought an annual plan', es: 'Un cliente compró el plan anual', zh: '有客户买了年度套餐', pt: 'Um cliente comprou o plano anual' },
    text: { ru: 'Кто-то настолько верит в тебя, что заплатил за год вперёд. Больше, чем ты сам.', en: 'Someone believes in you enough to pay a year upfront. More than you do.', es: 'Alguien cree tanto en ti que pagó un año por adelantado. Más que tú mismo.', zh: '有人对你的信心大到预付了一整年。比你对自己的信心还足。', pt: 'Alguém acredita tanto em você que pagou um ano adiantado. Mais do que você mesmo.' },
    fx: { money: 0, motivation: 5 }, // money добавится в движке: price × 10
  },
  {
    id: 'golem_hold',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.payments && s.mrr > 100,
    title: { ru: 'Gold Golem заморозил выплаты', en: 'Gold Golem froze your payouts', es: 'Gold Golem congeló tus pagos', zh: 'Gold Golem 冻结了你的提现', pt: 'O Gold Golem congelou seus repasses' },
    text: { ru: '«Подозрительная активность: вам заплатили». Разбирательство займёт время.', en: '"Suspicious activity: someone paid you." The review will take a while.', es: '«Actividad sospechosa: alguien te pagó». La revisión llevará su tiempo.', zh: '"可疑活动:居然有人给你付钱。"审核需要一段时间。', pt: '"Atividade suspeita: alguém te pagou." A análise vai demorar.' },
    fx: { money: -200, motivation: -3 },
  },
  {
    id: 'refund_wave',
    cat: 'money', char: 'churn_demon',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 5,
    title: { ru: 'Волна рефандов', en: 'A refund wave', es: 'Una ola de reembolsos', zh: '退款潮来了', pt: 'Uma onda de reembolsos' },
    text: { ru: 'Трое «купили случайно». Один — дважды. Талант.', en: 'Three "bought by accident". One of them — twice. Talented.', es: 'Tres «compraron por accidente». Uno de ellos, dos veces. Talento.', zh: '三个人"不小心买了"。其中一位不小心了两次。有天赋。', pt: 'Três "compraram sem querer". Um deles, duas vezes. Talento.' },
    fx: { money: -150, churnPct: 0.05 },
  },
  {
    id: 'indie_grant',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 1, traction: 1 },
    title: { ru: 'Грант для инди-мейкеров', en: 'An indie maker grant', es: 'Una beca para makers indie', zh: '独立开发者补助金', pt: 'Uma bolsa para makers indie' },
    text: { ru: 'Фонд «Маленькие Гильдии» перевёл $1000 без всяких условий. Бывает и такое.', en: 'The "Small Guilds" fund wired you $1000, no strings attached. It happens.', es: 'El fondo «Pequeños Gremios» te transfirió $1000 sin condiciones. A veces pasa.', zh: '"小公会"基金会无条件给你打了 $1000。这种事也是有的。', pt: 'O fundo "Pequenas Guildas" transferiu $1000 sem nenhuma condição. Acontece.' },
    fx: { money: 1000, motivation: 4 },
  },
  {
    id: 'dragon_coffee',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Дракон зовёт на кофе', en: 'The dragon invites you for coffee', es: 'El dragón te invita a un café', zh: '巨龙约你喝咖啡', pt: 'O dragão te chama para um café' },
    text: { ru: '«Просто поболтать». Драконы никогда не «просто болтают», но нетворкинг есть нетворкинг.', en: '"Just to chat." Dragons never "just chat", but networking is networking.', es: '«Solo para charlar». Los dragones nunca «solo charlan», pero el networking es el networking.', zh: '"就随便聊聊。"龙从来不"随便聊聊",但人脉就是人脉。', pt: '"Só para bater um papo." Dragões nunca "só batem papo", mas networking é networking.' },
    choices: [
      { label: { ru: 'Пойти (−2⚡)', en: 'Go (−2⚡)', es: 'Ir (−2⚡)', zh: '去(−2⚡)', pt: 'Ir (−2⚡)' }, fx: { energy: -2, audience: 30 } },
      { label: { ru: 'Работать', en: 'Keep working', es: 'Seguir trabajando', zh: '继续干活', pt: 'Continuar trabalhando' }, fx: {} },
    ],
  },
  {
    id: 'double_charge_bug',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Баг биллинга: двойное списание', en: 'Billing bug: double charge', es: 'Bug de facturación: cobro doble', zh: '账单 bug:重复扣款', pt: 'Bug de cobrança: cobrança em dobro' },
    text: { ru: 'Ты случайно списал с юзеров дважды. Они пока не заметили. Пока.', en: 'You accidentally charged users twice. They haven\'t noticed. Yet.', es: 'Cobraste a los usuarios dos veces sin querer. Aún no se han dado cuenta. Aún.', zh: '你不小心向用户扣了两次款。他们还没发现。暂时。', pt: 'Você cobrou os usuários duas vezes sem querer. Eles ainda não perceberam. Ainda.' },
    choices: [
      { label: { ru: 'Вернуть и извиниться публично', en: 'Refund and apologize publicly', es: 'Reembolsar y disculparse en público', zh: '退款并公开道歉', pt: 'Reembolsar e pedir desculpas em público' }, fx: { money: -100, motivation: 4, audience: 40 } },
      { label: { ru: 'Промолчать', en: 'Say nothing', es: 'No decir nada', zh: '装作没事', pt: 'Ficar quieto' }, fx: {}, risk: { prob: 0.5, fx: { motivation: -8, churnPct: 0.08 }, label: { ru: 'Заметили. Тред «осторожно, скам»', en: 'They noticed. A "beware, scam" thread', es: 'Se dieron cuenta. Un hilo de «cuidado, estafa»', zh: '被发现了。出现了"小心,骗子"的帖子', pt: 'Perceberam. Uma thread de "cuidado, golpe"' } } },
    ],
  },
  // ── ЮЗЕРЫ ────────────────────────────────────────────────
  {
    id: 'churn_demon_night',
    cat: 'users', char: 'churn_demon',
    stageW: { garage: 0, traction: 3 },
    requires: (s) => s.paid >= 5,
    title: { ru: 'Churn-демон приходил ночью', en: 'The churn demon came at night', es: 'El demonio del churn vino de noche', zh: 'churn 恶魔夜里来过', pt: 'O demônio do churn veio à noite' },
    text: { ru: 'Минус несколько клиентов. Причина отписки: «другое». Всегда «другое».', en: 'A few clients gone. Cancellation reason: "other". It\'s always "other".', es: 'Varios clientes menos. Motivo de la baja: «otro». Siempre es «otro».', zh: '少了几个客户。退订原因:"其他"。永远是"其他"。', pt: 'Menos alguns clientes. Motivo do cancelamento: "outro". É sempre "outro".' },
    fx: { churnPct: 0.15, motivation: -4 },
  },
  {
    id: 'feature_blackmail',
    cat: 'users', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: '«Без этой фичи я уйду»', en: '"Without this feature I\'m leaving"', es: '«Sin esta feature me voy»', zh: '"没有这个功能我就走"', pt: '"Sem essa feature eu vou embora"' },
    text: { ru: 'Юзер за $19 требует фичу на месяц разработки. Ловушка для добрых.', en: 'A $19 user demands a month-long feature. A trap for the kind-hearted.', es: 'Un usuario de $19 exige una feature de un mes de desarrollo. Una trampa para gente buena.', zh: '一个每月 $19 的用户要求一个得开发一个月的功能。专坑好人的陷阱。', pt: 'Um usuário de $19 exige uma feature de um mês de trabalho. Uma armadilha para os bonzinhos.' },
    choices: [
      { label: { ru: 'Сделать фичу (−4⚡)', en: 'Build the feature (−4⚡)', es: 'Hacer la feature (−4⚡)', zh: '做这个功能(−4⚡)', pt: 'Fazer a feature (−4⚡)' }, fx: { energy: -4, bugs: 1 } },
      { label: { ru: 'Вежливо отказать', en: 'Politely decline', es: 'Negarse amablemente', zh: '礼貌拒绝', pt: 'Recusar educadamente' }, fx: { paid: -1, motivation: -1 } },
    ],
  },
  {
    id: 'love_letter',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.lastSignups > 0 || s.paid > 0,
    title: { ru: 'Хвалебное письмо', en: 'A love letter', es: 'Una carta de amor', zh: '一封表白信', pt: 'Uma carta de amor' },
    text: { ru: '«Спасибо, что вы есть». Ради таких писем всё и затевалось (и ради $10k MRR).', en: '"Thank you for existing." This is what it\'s all for (that, and $10k MRR).', es: '«Gracias por existir». Para esto se montó todo (para esto y para los $10k de MRR).', zh: '"谢谢你们的存在。"当初折腾这一切,就是为了这样的信(以及 $10k MRR)。', pt: '"Obrigado por existirem." É para isso que tudo foi feito (isso, e os $10k de MRR).' },
    fx: { motivation: 7 },
  },
  {
    id: 'interview_gold',
    cat: 'users', char: 'oracle_analyst',
    stageW: { garage: 2, traction: 1 },
    requires: (s) => s.stats.totalSignups > 0,
    title: { ru: 'Золотой инсайт из интервью', en: 'A golden interview insight', es: 'Un insight de oro en una entrevista', zh: '访谈挖到金子级洞察', pt: 'Um insight de ouro numa entrevista' },
    text: { ru: 'Юзер случайно рассказал, за что он НА САМОМ ДЕЛЕ готов платить. Записывай!', en: 'A user accidentally revealed what they would ACTUALLY pay for. Write it down!', es: 'Un usuario reveló sin querer por qué pagaría DE VERDAD. ¡Apúntalo!', zh: '用户不小心说漏了嘴:他【真正】愿意为什么买单。快记下来!', pt: 'Um usuário revelou sem querer pelo que ele pagaria DE VERDADE. Anota!' },
    fx: { pmfBonus: 0.04 },
  },
  {
    id: 'pricing_complaint',
    cat: 'users', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: '«Дороговато для такого»', en: '"A bit pricey for this"', es: '«Algo caro para lo que es»', zh: '"就这还挺贵"', pt: '"Meio caro para isso"' },
    text: { ru: 'Юзер сравнил тебя с бесплатной таблицей в Excel. Больно, потому что отчасти правда.', en: 'A user compared you to a free Excel sheet. It hurts because it\'s partly true.', es: 'Un usuario te comparó con una hoja de Excel gratis. Duele porque en parte es verdad.', zh: '有用户拿你和免费的 Excel 表格作比较。扎心,因为有几分道理。', pt: 'Um usuário te comparou com uma planilha grátis do Excel. Dói porque é parcialmente verdade.' },
    fx: { motivation: -2 },
  },
  {
    id: 'feature_wave',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Пять юзеров просят одно и то же', en: 'Five users ask for the same thing', es: 'Cinco usuarios piden lo mismo', zh: '五个用户要同一个东西', pt: 'Cinco usuários pedem a mesma coisa' },
    text: { ru: 'Когда пятеро просят одно — это не фича-реквест, это дорожная карта.', en: 'When five people ask for the same thing, it\'s not a request — it\'s a roadmap.', es: 'Cuando cinco personas piden lo mismo, no es un feature request: es un roadmap.', zh: '五个人都要同一个东西,那就不是需求申请了,那是路线图。', pt: 'Quando cinco pessoas pedem a mesma coisa, não é feature request — é roadmap.' },
    fx: { pmfBonus: 0.03, motivation: 2 },
  },
  {
    id: 'churn_survey',
    cat: 'users', char: 'churn_demon',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Узнал, почему уходят', en: 'You learned why they leave', es: 'Descubriste por qué se van', zh: '你搞清了用户流失的原因', pt: 'Você descobriu por que eles saem' },
    text: { ru: 'Разослал опрос ушедшим. Ответил один, но честно. Теперь ты знаешь.', en: 'Surveyed churned users. One replied, but honestly. Now you know.', es: 'Encuestaste a los que se fueron. Respondió uno, pero con honestidad. Ahora lo sabes.', zh: '给流失用户发了问卷。只有一个人回复,但说了实话。现在你知道了。', pt: 'Mandou pesquisa para quem cancelou. Um respondeu, mas com sinceridade. Agora você sabe.' },
    fx: { quality: 0.03 },
  },
  {
    id: 'user_hug',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 1, traction: 1 },
    requires: (s) => s.paid >= 1,
    title: { ru: 'Юзер предложил помощь', en: 'A user offered to help', es: 'Un usuario ofreció su ayuda', zh: '用户主动要帮忙', pt: 'Um usuário se ofereceu para ajudar' },
    text: { ru: '«Могу написать пару постов про вас, мне не сложно». Комьюнити — суперсила инди.', en: '"I can write a couple of posts about you, no big deal." Community is the indie superpower.', es: '«Puedo escribir un par de posts sobre vosotros, no me cuesta nada». La comunidad es el superpoder indie.', zh: '"我可以帮你们写几篇推荐,举手之劳。"社区就是独立开发者的超能力。', pt: '"Posso escrever uns posts sobre vocês, sem problema nenhum." Comunidade é o superpoder indie.' },
    fx: { audience: 50, motivation: 3 },
  },
  {
    id: 'elf_redesign_offer',
    cat: 'users', char: 'elf_designer',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.landing > 0 && s.landing < 0.8,
    title: { ru: 'Эльфийка предлагает редизайн', en: 'The elf offers a redesign', es: 'La elfa propone un rediseño', zh: '精灵设计师提议重新设计', pt: 'A elfa propõe um redesign' },
    text: { ru: '«Твой лендинг выглядит как таверна после драки. $400 — и будет эльфийский сад».', en: '"Your landing looks like a tavern after a brawl. $400 and it\'ll be an elven garden."', es: '«Tu landing parece una taberna después de una pelea. Por $400 será un jardín élfico».', zh: '"你的落地页像打完群架的酒馆。给 $400,我还你一座精灵花园。"', pt: '"Sua landing parece uma taverna depois de uma briga. Por $400 vira um jardim élfico."' },
    choices: [
      { label: { ru: 'Заплатить $400', en: 'Pay $400', es: 'Pagar $400', zh: '付 $400', pt: 'Pagar $400' }, fx: { money: -400, landing: 0.2 } },
      { label: { ru: 'Сам сделаю', en: 'I\'ll do it myself', es: 'Lo hago yo mismo', zh: '我自己来', pt: 'Eu mesmo faço' }, fx: {} },
    ],
  },
  {
    id: 'server_bill_shock',
    cat: 'money', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Счёт за инфру удивил', en: 'A surprising infra bill', es: 'La factura de infra sorprendió', zh: '基础设施账单吓你一跳', pt: 'A conta da infra surpreendeu' },
    text: { ru: 'Забытый тестовый воркер месяц крутился в проде. Гном ничего не заметил (пил пиво).', en: 'A forgotten test worker ran in prod for a month. The dwarf noticed nothing (beer).', es: 'Un worker de prueba olvidado giró un mes entero en producción. El enano no notó nada (cerveza).', zh: '一个被遗忘的测试 worker 在生产环境跑了一个月。矮人什么都没发现(在喝啤酒)。', pt: 'Um worker de teste esquecido rodou um mês em produção. O anão não notou nada (cerveja).' },
    fx: { money: -120 },
  },
  {
    id: 'first_fan_art',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.audience >= 200,
    title: { ru: 'Фан-арт твоего логотипа', en: 'Fan art of your logo', es: 'Fan art de tu logo', zh: '有人给你的 logo 画了同人图', pt: 'Fan art do seu logo' },
    text: { ru: 'Кто-то нарисовал твой логотип в стиле аниме. Это странно. И почётно.', en: 'Someone drew your logo in anime style. It\'s weird. And an honor.', es: 'Alguien dibujó tu logo en estilo anime. Es raro. Y un honor.', zh: '有人把你的 logo 画成了动漫风。很怪。也很光荣。', pt: 'Alguém desenhou seu logo em estilo anime. É estranho. E uma honra.' },
    fx: { motivation: 5, audience: 30 },
  },
  // ── ПОЗДНЯЯ СТАДИЯ (Тракшн) ──────────────────────────────
  {
    id: 'dragon_exit',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.mrr >= 5000,
    title: { ru: 'Дракон хочет купить гильдию', en: 'The dragon wants to buy the guild' },
    text: { ru: '«Продай мне всё. Три годовые выручки, золотом, сегодня. Или дожимай свои $10k сам — если доживёшь».', en: '"Sell me everything. Three annual revenues, in gold, today. Or grind to your $10k alone — if you survive."' },
    choices: [
      { label: { ru: 'Продать компанию (экзит!)', en: 'Sell the company (exit!)' }, fx: { end: 'sold' } },
      { label: { ru: 'Отказаться. Идём до конца', en: 'Decline. We go all the way' }, fx: { motivation: 6 } },
    ],
  },
  {
    id: 'senior_wants_in',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.mrr >= 2000,
    title: { ru: 'Сеньор из BigTech просится к тебе', en: 'A BigTech senior wants to join you' },
    text: { ru: '«Устал от митингов. Возьми меня за 5% и зарплату. Я перепишу всё за месяц (реально за три)».', en: '"Tired of meetings. Take me for 5% and a salary. I\'ll rewrite everything in a month (three, realistically)."' },
    choices: [
      { label: { ru: 'Взять (−$2000, 5% доли, +качество)', en: 'Hire (−$2000, 5% equity, +quality)' }, fx: { money: -2000, share: 0.05, quality: 0.15 } },
      { label: { ru: 'Вежливо отказать', en: 'Politely decline' }, fx: {} },
    ],
  },
  {
    id: 'vc_cold_email',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 0, traction: 2 },
    title: { ru: 'Холодное письмо от VC', en: 'A cold email from a VC' },
    text: { ru: '«Восхищаемся вашим путём! Найдётся 30 минут?» — письмо, отправленное 400 фаундерам сегодня.', en: '"We admire your journey! Got 30 minutes?" — an email sent to 400 founders today.' },
    choices: [
      { label: { ru: 'Сходить на звонок (−2⚡)', en: 'Take the call (−2⚡)' }, fx: { energy: -2, audience: 100 } },
      { label: { ru: 'В архив', en: 'Archive' }, fx: { motivation: 2 } },
    ],
  },
  {
    id: 'competitor_dumping',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 10,
    title: { ru: 'Лич демпингует', en: 'The lich is dumping prices' },
    text: { ru: 'Он сделал свой тариф в 3 раза дешевле твоего. Себе в убыток. Некроманты не считают юнит-экономику.', en: 'His plan is now 3× cheaper than yours. At a loss. Necromancers don\'t do unit economics.' },
    fx: { churnPct: 0.08, motivation: -3 },
  },
  {
    id: 'whale_custom_request',
    cat: 'users', char: 'dragon_investor',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 15,
    title: { ru: 'Крупный клиент просит кастом', en: 'A big client wants custom work' },
    text: { ru: '«Нужна интеграция с нашей внутренней системой на COBOL. Заплатим хорошо».', en: '"We need an integration with our internal COBOL system. We pay well."' },
    choices: [
      { label: { ru: 'Сделать (−6⚡, +$1500)', en: 'Build it (−6⚡, +$1500)' }, fx: { energy: -6, money: 1500 } },
      { label: { ru: 'Отказаться: фокус', en: 'Decline: focus' }, fx: { motivation: 2 } },
    ],
  },
  {
    id: 'conference_talk',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.audience >= 500,
    title: { ru: 'Зовут выступить на конференции', en: 'Invited to speak at a conference' },
    text: { ru: '«IndieConf, зал на 300 гномов. Тема: как выжить соло». Страшно. Полезно. Страшно полезно.', en: '"IndieConf, a hall of 300 dwarves. Topic: surviving solo." Scary. Useful. Scary useful.' },
    choices: [
      { label: { ru: 'Выступить (−5⚡)', en: 'Speak (−5⚡)' }, fx: { energy: -5, audience: 300, motivation: 5 } },
      { label: { ru: 'Отказаться', en: 'Decline' }, fx: { motivation: -2 } },
    ],
  },
  {
    id: 'marketplace_invite',
    cat: 'market', char: 'gnome_devops',
    stageW: { garage: 0, traction: 2 },
    title: { ru: 'Зовут в маркетплейс интеграций', en: 'Invited to an integrations marketplace' },
    text: { ru: 'Крупная платформа добавила тебя в каталог. Их трафик — теперь немного и твой.', en: 'A big platform listed you in their catalog. Their traffic is a little bit yours now.' },
    fx: { traffic: { mult: 1.5, days: 7 } },
  },
  {
    id: 'security_scare',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 10,
    title: { ru: 'Паника: «у вас дыра в безопасности?»', en: 'Panic: "do you have a security hole?"' },
    text: { ru: 'Аноним в DM: «Я нашёл уязвимость». Может, белый хакер. Может, гоблин с фантазией.', en: 'An anon DM: "I found a vulnerability." Maybe a white hat. Maybe a goblin with imagination.' },
    choices: [
      { label: { ru: 'Заказать аудит ($400)', en: 'Order an audit ($400)' }, fx: { money: -400, motivation: 3 } },
      { label: { ru: 'Игнорировать', en: 'Ignore' }, fx: {}, risk: { prob: 0.3, fx: { churnPct: 0.15, motivation: -6 }, label: { ru: 'Дыра была настоящей. Тред «осторожно» уже в топе', en: 'The hole was real. The "beware" thread is trending' } } },
    ],
  },
  {
    id: 'press_article',
    cat: 'social', char: 'oracle_analyst',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.mrr >= 1500,
    title: { ru: 'Журналист пишет про инди-волну', en: 'A journalist covers the indie wave' },
    text: { ru: 'Статья «Соло-фаундеры против корпораций» — и ты в примерах. С опечаткой в имени, но в примерах.', en: 'An article "Solo founders vs corporations" — and you\'re featured. With your name misspelled, but featured.' },
    fx: { traffic: { mult: 2, days: 3 }, audience: 200 },
  },
  {
    id: 'ab_test_broke_checkout',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.payments,
    title: { ru: 'A/B-тест сломал чекаут', en: 'An A/B test broke the checkout' },
    text: { ru: 'Вариант Б показывал кнопку оплаты только по вторникам. Сегодня четверг. Было три четверга.', en: 'Variant B showed the pay button only on Tuesdays. It\'s Thursday. There have been three Thursdays.' },
    fx: { money: -200, bugs: 1, motivation: -3 },
  },
  {
    id: 'support_burnout',
    cat: 'personal', char: 'support_goblin',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.hires.includes('support_goblin'),
    title: { ru: 'Саппорт-гоблин выгорает', en: 'The support goblin is burning out' },
    text: { ru: '«Триста тикетов, и в каждом — „не работает“. Без деталей. Мне нужен отпуск или премия».', en: '"Three hundred tickets, each says \'doesn\'t work\'. No details. I need a vacation or a bonus."' },
    choices: [
      { label: { ru: 'Премия $300', en: 'A $300 bonus' }, fx: { money: -300 } },
      { label: { ru: 'Потерпит', en: 'He\'ll manage' }, fx: {}, risk: { prob: 0.4, fx: { churnPct: 0.1, motivation: -4 }, label: { ru: 'Гоблин отвечал юзерам «сам разберись». Они разобрались — ушли', en: 'The goblin told users "figure it out". They did — and left' } } },
    ],
  },
  {
    id: 'tax_audit_big',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.mrr >= 2000,
    title: { ru: 'Налоговый аудит', en: 'A tax audit' },
    text: { ru: 'Сова принесла толстую папку: «Уху. Поговорим о ваших „расходах на кофе“ за последний квартал».', en: 'The owl brought a thick folder: "Hoo. Let\'s discuss your \'coffee expenses\' for the last quarter."' },
    choices: [
      { label: { ru: 'Нанять бухгалтера ($500)', en: 'Hire an accountant ($500)' }, fx: { money: -500 } },
      { label: { ru: 'Разобраться самому (−4⚡)', en: 'Handle it yourself (−4⚡)' }, fx: { energy: -4, motivation: -4 } },
    ],
  },
  {
    id: 'lich_buys_competitor',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 0, traction: 2 },
    title: { ru: 'Лич скупает конкурентов', en: 'The lich is acquiring competitors' },
    text: { ru: 'Третья покупка за месяц. Некромант собирает армию из мёртвых стартапов. Рынок нервничает.', en: 'Third acquisition this month. The necromancer builds an army of dead startups. The market is nervous.' },
    fx: { demand: { mult: 0.8, days: 5 }, motivation: -3 },
  },
  {
    id: 'influencer_review_offer',
    cat: 'social', char: 'elf_designer',
    stageW: { garage: 0, traction: 2 },
    title: { ru: 'Топ-инфлюенсер предлагает обзор', en: 'A top influencer offers a review' },
    text: { ru: '«500 голды — и мой миллион подписчиков узнает о вас. Честный обзор. Ну, почти честный».', en: '"500 gold — and my million followers hear about you. An honest review. Well, almost honest."' },
    choices: [
      { label: { ru: 'Заплатить $500', en: 'Pay $500' }, fx: { money: -500, audience: 400, traffic: { mult: 1.6, days: 3 } } },
      { label: { ru: 'Дорого. Пас', en: 'Too pricey. Pass' }, fx: {} },
    ],
  },
  {
    id: 'scaling_pain',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 30,
    title: { ru: 'Рост упёрся в архитектуру', en: 'Growth hit an architecture wall' },
    text: { ru: 'То, что держало 10 юзеров, кряхтит под сотней. Гном смотрит на твой код и качает головой.', en: 'What held 10 users wheezes under a hundred. The dwarf looks at your code and shakes his head.' },
    choices: [
      { label: { ru: 'Рефакторинг (−8⚡)', en: 'Refactor (−8⚡)' }, fx: { energy: -8, quality: 0.08 } },
      { label: { ru: 'Залить железом (+$100/мес инфры)', en: 'Throw hardware at it (+$100/mo infra)' }, fx: { infra: 100 } },
    ],
  },
  {
    id: 'user_champion_team',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 5,
    title: { ru: 'Юзер-чемпион привёл свою команду', en: 'A champion user brought their team' },
    text: { ru: 'Паладин показал продукт всему своему ордену. Орден оформил подписки. Так выглядит настоящий PMF.', en: 'The paladin showed the product to his whole order. The order subscribed. This is what real PMF looks like.' },
    fx: { paid: 3, motivation: 5 },
  },
  {
    id: 'platform_api_change',
    cat: 'tech', char: 'oracle_analyst',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.channels.social > 1 || s.channels.email > 1,
    title: { ru: 'Платформа меняет правила API', en: 'The platform changes API rules' },
    text: { ru: 'Xitter теперь берёт деньги за то, что раньше было бесплатным. Классика жанра «сначала раздай, потом продай».', en: 'Xitter now charges for what used to be free. The classic "give first, charge later" move.' },
    choices: [
      { label: { ru: 'Платить ($150)', en: 'Pay up ($150)' }, fx: { money: -150 } },
      { label: { ru: 'Мигрировать на другой канал (−4⚡)', en: 'Migrate to another channel (−4⚡)' }, fx: { energy: -4, traffic: { mult: 0.8, days: 4 } } },
    ],
  },
  {
    id: 'annual_renewal_wave',
    cat: 'money', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.annualPlans && s.paid >= 10,
    title: { ru: 'Волна годовых продлений', en: 'A wave of annual renewals' },
    text: { ru: 'Годовые клиенты продлились почти все разом. Голем-платёжка работал сверхурочно.', en: 'Annual customers renewed almost all at once. The payment golem worked overtime.' },
    fx: { money: 800, motivation: 4 },
  },
]
