import type { EventDef } from '../types'

// 52 события. Вес по стадиям; requires отсекают бессмысленные (нет прода — не падает прод)
export const EVENTS: EventDef[] = [
  // ── РЫНОК ────────────────────────────────────────────────
  {
    id: 'lich_copied',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Лич скопировал твою фичу', en: 'The lich copied your feature' },
    text: { ru: '«Некроманты не изобретают. Некроманты поднимают чужое», — пишет он в чейнджлоге.', en: '"Necromancers don\'t invent. Necromancers raise what\'s dead," says his changelog.' },
    fx: { traffic: { mult: 0.7, days: 5 }, motivation: -3 },
  },
  {
    id: 'niche_hype',
    cat: 'market', char: 'oracle_analyst',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Ниша хайпанула', en: 'Your niche is hyped' },
    text: { ru: 'Кто-то крупный написал тред «будущее за этим». Спрос ×2 на неделю.', en: 'Someone big tweeted "this is the future". Demand ×2 for a week.' },
    fx: { demand: { mult: 2, days: 7 } },
  },
  {
    id: 'donor_price_up',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.donorResearched,
    title: { ru: 'Донор поднял цены', en: 'Your donor raised prices' },
    text: { ru: 'Конкурент-донор поднял цены ×2. Его юзеры смотрят по сторонам. Например, на тебя.', en: 'The donor competitor doubled prices. Their users are looking around. At you, for example.' },
    fx: { pmfBonus: 0.03 },
  },
  {
    id: 'competitor_died',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Конкурент закрылся', en: 'A competitor shut down' },
    text: { ru: '«Спасибо за путешествие» — пост на их лендинге. Их трафик ищет новый дом.', en: '"Thanks for the journey" — says their landing page. Their traffic seeks a new home.' },
    fx: { traffic: { mult: 1.4, days: 5 } },
  },
  {
    id: 'market_cooldown',
    cat: 'market', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    title: { ru: 'Рынок остыл', en: 'The market cooled off' },
    text: { ru: 'Хайп ушёл в соседнюю нишу. Спрос −40% на несколько дней.', en: 'The hype moved next door. Demand −40% for a few days.' },
    fx: { demand: { mult: 0.6, days: 5 } },
  },
  {
    id: 'lich_launch_day',
    cat: 'market', char: 'lich_competitor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Лич лончится в твой день', en: 'The lich launches on your day' },
    text: { ru: 'Он вышел на Product Cave с «AI-powered» версией твоего продукта. Внимание рынка — не твоё.', en: 'He hit Product Cave with an "AI-powered" version of your product. The market\'s attention is not yours.' },
    fx: { traffic: { mult: 0.6, days: 3 } },
  },
  {
    id: 'copycat_you',
    cat: 'market', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Тебя склонировали за выходные', en: 'You got cloned over a weekend' },
    text: { ru: 'Некий студент собрал клон «за 2 вечера» и написал об этом тред.', en: 'Some student built a clone "in 2 evenings" and wrote a thread about it.' },
    choices: [
      { label: { ru: 'Написать разбор, почему твой лучше (−2⚡)', en: 'Write a breakdown why yours is better (−2⚡)' }, fx: { energy: -2, audience: 100 } },
      { label: { ru: 'Игнорировать', en: 'Ignore' }, fx: { motivation: -4 } },
    ],
  },
  // ── ТЕХНИЧЕСКИЕ ──────────────────────────────────────────
  {
    id: 'prod_down_friday',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.deployed,
    title: { ru: 'Прод упал. Пятница, 23:40', en: 'Prod is down. Friday, 11:40pm' },
    text: { ru: 'Гном-девопс уже здесь. Требует пива и $200. Или чини сам.', en: 'The dwarf devops is here. Demands beer and $200. Or fix it yourself.' },
    choices: [
      { label: { ru: 'Чинить ночью самому', en: 'Fix it overnight yourself' }, fx: { energy: -4, motivation: -5 } },
      { label: { ru: 'Заплатить гному $200', en: 'Pay the dwarf $200' }, fx: { money: -200 } },
      { label: { ru: 'Забить до понедельника', en: 'Ignore until Monday' }, fx: {}, risk: { prob: 0.5, fx: { churnPct: 0.2, motivation: -4 }, label: { ru: 'Юзеры заметили. Churn-демон доволен', en: 'Users noticed. The churn demon is pleased' } } },
    ],
  },
  {
    id: 'wyvercel_pricing',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Wyvercel сменил тарифы', en: 'Wyvercel changed pricing' },
    text: { ru: '«Мы упрощаем тарифы» = теперь дороже. Классика.', en: '"We are simplifying pricing" = it\'s more expensive now. A classic.' },
    fx: { infra: 30 },
  },
  {
    id: 'critical_bug_client',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 3 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Критический баг у крупного клиента', en: 'Critical bug at a big client' },
    text: { ru: 'Скриншот в саппорт, три восклицательных знака, слово «СРОЧНО» капсом.', en: 'A screenshot in support, three exclamation marks, the word "URGENT" in caps.' },
    choices: [
      { label: { ru: 'Чинить ночью (−мотивация)', en: 'Fix overnight (−motivation)' }, fx: { motivation: -6, bugs: -2 } },
      { label: { ru: 'Забить', en: 'Ignore' }, fx: {}, risk: { prob: 0.7, fx: { churnPct: 0.12 }, label: { ru: 'Клиент ушёл и увёл друзей', en: 'The client left and took friends along' } } },
    ],
  },
  {
    id: 'ddos_goblins',
    cat: 'tech', char: 'goblin_hater',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Гоблины дудосят', en: 'Goblins are DDoSing you' },
    text: { ru: 'Кто-то из Dungeon Boards обиделся на твой пост. Сайт лежит.', en: 'Someone from Dungeon Boards got offended by your post. The site is down.' },
    choices: [
      { label: { ru: 'Оплатить щит CDN ($150)', en: 'Pay for a CDN shield ($150)' }, fx: { money: -150 } },
      { label: { ru: 'Переждать', en: 'Wait it out' }, fx: { traffic: { mult: 0.5, days: 2 } } },
    ],
  },
  {
    id: 'data_loss',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Потерял кусок данных', en: 'You lost some data' },
    text: { ru: 'Бекапы? Какие бекапы. Ты же соло-фаундер, у тебя нет времени на бекапы.', en: 'Backups? What backups. You\'re a solo founder, no time for backups.' },
    fx: { bugs: 2, motivation: -4 },
  },
  {
    id: 'api_deprecated',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.progress >= 40,
    title: { ru: 'Ключевая зависимость всё', en: 'A key dependency is dead' },
    text: { ru: 'Библиотека, на которой всё держится, помечена deprecated. Мейнтейнер ушёл разводить овец.', en: 'The library holding everything together is deprecated. The maintainer left to herd sheep.' },
    choices: [
      { label: { ru: 'День на миграцию (−6⚡)', en: 'A day of migration (−6⚡)' }, fx: { energy: -6 } },
      { label: { ru: 'Работает — не трогай', en: "If it works, don't touch it" }, fx: { bugs: 3 } },
    ],
  },
  {
    id: 'wyvercel_grant',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 2, traction: 1 },
    requires: (s) => s.deployed,
    title: { ru: 'Wyvercel дал кредиты', en: 'Wyvercel gave you credits' },
    text: { ru: 'Программа поддержки инди-магов: $100 кредитов на инфру. Мелочь, а приятно.', en: 'Indie mage support program: $100 in infra credits. Small, but nice.' },
    fx: { money: 100 },
  },
  {
    id: 'gnome_cache_tip',
    cat: 'tech', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Гном посоветовал кеш', en: 'The dwarf suggested caching' },
    text: { ru: '«Поставь кеш, балда» — сказал гном. Инфра подешевела.', en: '"Add a cache, you dolt," said the dwarf. Infra got cheaper.' },
    fx: { infra: -10 },
  },
  // ── СОЦСЕТИ / ЛОНЧ ───────────────────────────────────────
  {
    id: 'post_viral',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.audience >= 20,
    title: { ru: 'Пост завирусился', en: 'Your post went viral' },
    text: { ru: 'Алгоритм Xitter сегодня на твоей стороне. Аудитория ×3.', en: 'The Xitter algorithm is on your side today. Audience ×3.' },
    fx: { audienceMult: 3 },
  },
  {
    id: 'goblin_comments',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 2, traction: 2 },
    requires: (s) => s.audience >= 10,
    title: { ru: 'Гоблины в комментах', en: 'Goblins in the comments' },
    text: { ru: '«поделка», «такое уже есть», «а почему не опенсорс?»', en: '"toy project", "this already exists", "why isn\'t it open source?"' },
    choices: [
      { label: { ru: 'Отвечать каждому (−2⚡)', en: 'Reply to each one (−2⚡)' }, fx: { energy: -2 }, risk: { prob: 0.4, fx: { motivation: -5 }, label: { ru: 'Затянуло в срач на 3 часа', en: 'Got dragged into a 3-hour flame war' } } },
      { label: { ru: 'Игнорировать', en: 'Ignore' }, fx: { motivation: -3 } },
    ],
  },
  {
    id: 'product_cave_feature',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Фичеринг на Product Cave', en: 'Featured on Product Cave' },
    text: { ru: 'Редакция пещеры выбрала тебя продуктом недели. Трафик ×3.', en: 'The cave editors picked you as product of the week. Traffic ×3.' },
    fx: { traffic: { mult: 3, days: 2 } },
  },
  {
    id: 'big_account_shitpost',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Шитпост про тебя от крупного аккаунта', en: 'A big account shitposted about you' },
    text: { ru: '«Индихакеры опять изобрели то, что было в 2009». 2 миллиона просмотров.', en: '"Indie hackers reinvented something from 2009 again." 2 million views.' },
    fx: { motivation: -6, audience: 80 },
  },
  {
    id: 'algo_change',
    cat: 'social', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.channels.social > 0.5,
    title: { ru: 'Xitter поменял алгоритм', en: 'Xitter changed the algorithm' },
    text: { ru: 'Теперь показывают только видео с котами. У тебя SaaS. Не с котами.', en: 'Now it only shows cat videos. You have a SaaS. Without cats.' },
    fx: { traffic: { mult: 0.7, days: 4 } },
  },
  {
    id: 'dm_collab',
    cat: 'social', char: 'elf_designer',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.audience >= 50,
    title: { ru: 'Микроинфлюенсер предлагает коллаб', en: 'A micro-influencer offers a collab' },
    text: { ru: '«Сделаю обзор за $150. У меня очень вовлечённая аудитория (мама и два гнома)».', en: '"I\'ll review it for $150. My audience is super engaged (my mom and two dwarves)."' },
    choices: [
      { label: { ru: 'Заплатить $150', en: 'Pay $150' }, fx: { money: -150, audience: 200 } },
      { label: { ru: 'Вежливо отказаться', en: 'Politely decline' }, fx: {} },
    ],
  },
  {
    id: 'paladin_thread',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: 'Фанат-паладин написал тред', en: 'The paladin fan wrote a thread' },
    text: { ru: '«Этот продукт изменил мой воркфлоу» — 12 твитов, все с эмодзи меча.', en: '"This product changed my workflow" — 12 tweets, all with sword emojis.' },
    fx: { motivation: 6, audience: 60 },
  },
  {
    id: 'hn_frontpage',
    cat: 'social', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Фронтпейдж Dungeon News', en: 'Dungeon News front page' },
    text: { ru: 'Трафик ×4. В комментах спорят о лицензии и почему ты не сделал это на Lisp.', en: 'Traffic ×4. The comments argue about your license and why you didn\'t use Lisp.' },
    fx: { traffic: { mult: 4, days: 1 }, motivation: -2 },
  },
  {
    id: 'seo_update',
    cat: 'social', char: 'oracle_analyst',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.channels.seo > 1,
    title: { ru: 'Кор-апдейт поисковика', en: 'Search engine core update' },
    text: { ru: 'Google перетасовал выдачу. Твои позиции просели «временно» (никто не знает, насколько).', en: 'Google reshuffled the results. Your rankings dipped "temporarily" (nobody knows for how long).' },
    fx: { traffic: { mult: 0.75, days: 7 } },
  },
  {
    id: 'opensource_clone',
    cat: 'social', char: 'lich_competitor',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Появился опенсорс-клон', en: 'An open-source clone appeared' },
    text: { ru: '«Как твой продукт, только бесплатно и с багами». 800 звёзд за сутки.', en: '"Like your product, but free and buggy." 800 stars overnight.' },
    choices: [
      { label: { ru: 'Паниковать', en: 'Panic' }, fx: { motivation: -4 } },
      { label: { ru: 'Публично похвалить (маркетинг!)', en: 'Publicly praise it (marketing!)' }, fx: { audience: 120 } },
    ],
  },
  {
    id: 'podcast_invite',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.audience >= 100,
    title: { ru: 'Позвали на подкаст', en: 'Invited to a podcast' },
    text: { ru: '«Гильдия одного: как выжить соло». Два часа разговоров, четыре слушателя, но какие!', en: '"Guild of One: surviving solo." Two hours of talk, four listeners — but what listeners!' },
    choices: [
      { label: { ru: 'Пойти (−4⚡)', en: 'Go (−4⚡)' }, fx: { energy: -4, audience: 150, motivation: 3 } },
      { label: { ru: 'Отказаться', en: 'Decline' }, fx: {} },
    ],
  },
  {
    id: 'mrr_screenshot_trend',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.mrr > 0,
    title: { ru: 'Тренд «покажи свой MRR»', en: '"Show your MRR" trend' },
    text: { ru: 'Все постят скриншоты дашбордов. Building in public — религия со своими обрядами.', en: 'Everyone posts dashboard screenshots. Building in public is a religion with rituals.' },
    fx: { audience: 120 },
  },
  // ── ЛИЧНЫЕ ───────────────────────────────────────────────
  {
    id: 'cold',
    cat: 'personal', char: 'gnome_devops',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Простуда', en: 'You caught a cold' },
    text: { ru: 'Горло болит, нос течёт, дедлайны сами себя не сдвинут (сдвинут).', en: 'Sore throat, runny nose. The deadlines won\'t move themselves (they will).' },
    fx: { sick: { energy: -4, days: 3 } },
  },
  {
    id: 'friend_vacation',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Друг зовёт в отпуск', en: 'A friend invites you on vacation' },
    text: { ru: '«Ты же сам себе начальник, отпросись у себя». Аргумент железный.', en: '"You\'re your own boss, ask yourself for time off." Solid argument.' },
    choices: [
      { label: { ru: 'Поехать (−$500)', en: 'Go (−$500)' }, fx: { money: -500, motivation: 15, energy: -10 } },
      { label: { ru: 'Отказаться', en: 'Decline' }, fx: { motivation: -6 } },
    ],
  },
  {
    id: 'job_offer',
    cat: 'personal', char: 'dragon_investor',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Оффер из найма', en: 'A job offer' },
    text: { ru: 'Бывший коллега: «У нас открылась позиция, х2 от твоей прошлой зарплаты. Подумай».', en: 'An ex-colleague: "We have an opening, 2x your old salary. Think about it."' },
    choices: [
      { label: { ru: 'Отказаться. Ты выбрал этот путь', en: 'Decline. You chose this path' }, fx: { motivation: 4 } },
      { label: { ru: 'Принять оффер (конец рана)', en: 'Accept the offer (run ends)' }, fx: { end: 'quit_job' } },
    ],
  },
  {
    id: 'back_pain',
    cat: 'personal', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    title: { ru: 'Спина передаёт привет', en: 'Your back says hi' },
    text: { ru: '14 часов за столом из «просто доделаю» превратились в визит к костоправу.', en: '14 hours at the desk of "just finishing up" turned into a chiropractor visit.' },
    fx: { sick: { energy: -2, days: 2 }, motivation: -2 },
  },
  {
    id: 'imposter',
    cat: 'personal', char: 'churn_demon',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Синдром самозванца', en: 'Impostor syndrome' },
    text: { ru: 'Все вокруг делают $30k MRR (в твитах). А ты кто вообще такой?', en: 'Everyone around makes $30k MRR (in tweets). Who even are you?' },
    choices: [
      { label: { ru: 'Сессия у барда-терапевта ($120)', en: 'A session with the bard therapist ($120)' }, fx: { money: -120, motivation: 6 } },
      { label: { ru: 'Перетерпеть', en: 'Push through' }, fx: { motivation: -8 } },
    ],
  },
  {
    id: 'old_friend_praise',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Старый друг гордится', en: 'An old friend is proud' },
    text: { ru: '«Слушай, я видел твой проект. Круто, что ты решился». Внезапно приятно.', en: '"Hey, I saw your project. Takes guts, respect." Unexpectedly nice.' },
    fx: { motivation: 8 },
  },
  {
    id: 'insomnia',
    cat: 'personal', char: 'churn_demon',
    stageW: { garage: 2, traction: 2 },
    title: { ru: 'Бессонница', en: 'Insomnia' },
    text: { ru: 'До трёх ночи листал чужие истории успеха. Утром — как будто тебя переехал голем.', en: 'Scrolled other people\'s success stories until 3am. Morning feels like a golem ran you over.' },
    fx: { energy: -3 },
  },
  {
    id: 'motivational_video',
    cat: 'personal', char: 'paladin_fan',
    stageW: { garage: 2, traction: 1 },
    title: { ru: 'Мотивационный ролик вместо работы', en: 'A motivational video instead of work' },
    text: { ru: '«Как я сделал $1M за год» — 40 минут. Работа не сделана, но настрой боевой.', en: '"How I made $1M in a year" — 40 minutes. No work done, but the spirit is high.' },
    fx: { energy: -1, motivation: 2 },
  },
  // ── ДЕНЬГИ ───────────────────────────────────────────────
  {
    id: 'dragon_invest',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 0, traction: 3 },
    requires: (s) => s.mrr >= 500 && s.investorShare === 0,
    title: { ru: 'Дракон-инвестор предлагает сделку', en: 'The dragon investor offers a deal' },
    text: { ru: '«$50,000 за 20% твоей пещеры. Драконы плохого не посоветуют. Драконам».', en: '"$50,000 for 20% of your cave. Dragons never give bad advice. To dragons."' },
    choices: [
      { label: { ru: 'Взять $50k (отдать 20% MRR)', en: 'Take $50k (give up 20% of MRR)' }, fx: { money: 50000, share: 0.2 } },
      { label: { ru: 'Отказаться. Bootstrapped и гордый', en: 'Decline. Bootstrapped and proud' }, fx: { motivation: 3 } },
    ],
  },
  {
    id: 'tax_owl_letter',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.money > 400,
    title: { ru: 'Письмо от налоговой совы', en: 'A letter from the tax owl' },
    text: { ru: '«Уху. Вы забыли подать форму 27-Б. Уху-ху». Совы не прощают.', en: '"Hoo. You forgot to file form 27-B. Hoo-hoo." Owls do not forgive.' },
    fx: { money: -300, motivation: -2 },
  },
  {
    id: 'annual_plan',
    cat: 'money', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 2,
    title: { ru: 'Клиент купил годовой план', en: 'A client bought an annual plan' },
    text: { ru: 'Кто-то настолько верит в тебя, что заплатил за год вперёд. Больше, чем ты сам.', en: 'Someone believes in you enough to pay a year upfront. More than you do.' },
    fx: { money: 0, motivation: 5 }, // money добавится в движке: price × 10
  },
  {
    id: 'golem_hold',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.payments && s.mrr > 100,
    title: { ru: 'Gold Golem заморозил выплаты', en: 'Gold Golem froze your payouts' },
    text: { ru: '«Подозрительная активность: вам заплатили». Разбирательство займёт время.', en: '"Suspicious activity: someone paid you." The review will take a while.' },
    fx: { money: -200, motivation: -3 },
  },
  {
    id: 'refund_wave',
    cat: 'money', char: 'churn_demon',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 5,
    title: { ru: 'Волна рефандов', en: 'A refund wave' },
    text: { ru: 'Трое «купили случайно». Один — дважды. Талант.', en: 'Three "bought by accident". One of them — twice. Talented.' },
    fx: { money: -150, churnPct: 0.05 },
  },
  {
    id: 'indie_grant',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 1, traction: 1 },
    title: { ru: 'Грант для инди-мейкеров', en: 'An indie maker grant' },
    text: { ru: 'Фонд «Маленькие Гильдии» перевёл $1000 без всяких условий. Бывает и такое.', en: 'The "Small Guilds" fund wired you $1000, no strings attached. It happens.' },
    fx: { money: 1000, motivation: 4 },
  },
  {
    id: 'dragon_coffee',
    cat: 'money', char: 'dragon_investor',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.launches > 0,
    title: { ru: 'Дракон зовёт на кофе', en: 'The dragon invites you for coffee' },
    text: { ru: '«Просто поболтать». Драконы никогда не «просто болтают», но нетворкинг есть нетворкинг.', en: '"Just to chat." Dragons never "just chat", but networking is networking.' },
    choices: [
      { label: { ru: 'Пойти (−2⚡)', en: 'Go (−2⚡)' }, fx: { energy: -2, audience: 30 } },
      { label: { ru: 'Работать', en: 'Keep working' }, fx: {} },
    ],
  },
  {
    id: 'double_charge_bug',
    cat: 'money', char: 'tax_owl',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Баг биллинга: двойное списание', en: 'Billing bug: double charge' },
    text: { ru: 'Ты случайно списал с юзеров дважды. Они пока не заметили. Пока.', en: 'You accidentally charged users twice. They haven\'t noticed. Yet.' },
    choices: [
      { label: { ru: 'Вернуть и извиниться публично', en: 'Refund and apologize publicly' }, fx: { money: -100, motivation: 4, audience: 40 } },
      { label: { ru: 'Промолчать', en: 'Say nothing' }, fx: {}, risk: { prob: 0.5, fx: { motivation: -8, churnPct: 0.08 }, label: { ru: 'Заметили. Тред «осторожно, скам»', en: 'They noticed. A "beware, scam" thread' } } },
    ],
  },
  // ── ЮЗЕРЫ ────────────────────────────────────────────────
  {
    id: 'churn_demon_night',
    cat: 'users', char: 'churn_demon',
    stageW: { garage: 0, traction: 3 },
    requires: (s) => s.paid >= 5,
    title: { ru: 'Churn-демон приходил ночью', en: 'The churn demon came at night' },
    text: { ru: 'Минус несколько клиентов. Причина отписки: «другое». Всегда «другое».', en: 'A few clients gone. Cancellation reason: "other". It\'s always "other".' },
    fx: { churnPct: 0.15, motivation: -4 },
  },
  {
    id: 'feature_blackmail',
    cat: 'users', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: '«Без этой фичи я уйду»', en: '"Without this feature I\'m leaving"' },
    text: { ru: 'Юзер за $19 требует фичу на месяц разработки. Ловушка для добрых.', en: 'A $19 user demands a month-long feature. A trap for the kind-hearted.' },
    choices: [
      { label: { ru: 'Сделать фичу (−4⚡)', en: 'Build the feature (−4⚡)' }, fx: { energy: -4, bugs: 1 } },
      { label: { ru: 'Вежливо отказать', en: 'Politely decline' }, fx: { paid: -1, motivation: -1 } },
    ],
  },
  {
    id: 'love_letter',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.lastSignups > 0 || s.paid > 0,
    title: { ru: 'Хвалебное письмо', en: 'A love letter' },
    text: { ru: '«Спасибо, что вы есть». Ради таких писем всё и затевалось (и ради $10k MRR).', en: '"Thank you for existing." This is what it\'s all for (that, and $10k MRR).' },
    fx: { motivation: 7 },
  },
  {
    id: 'interview_gold',
    cat: 'users', char: 'oracle_analyst',
    stageW: { garage: 2, traction: 1 },
    requires: (s) => s.stats.totalSignups > 0,
    title: { ru: 'Золотой инсайт из интервью', en: 'A golden interview insight' },
    text: { ru: 'Юзер случайно рассказал, за что он НА САМОМ ДЕЛЕ готов платить. Записывай!', en: 'A user accidentally revealed what they would ACTUALLY pay for. Write it down!' },
    fx: { pmfBonus: 0.04 },
  },
  {
    id: 'pricing_complaint',
    cat: 'users', char: 'goblin_hater',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.paid >= 1,
    title: { ru: '«Дороговато для такого»', en: '"A bit pricey for this"' },
    text: { ru: 'Юзер сравнил тебя с бесплатной таблицей в Excel. Больно, потому что отчасти правда.', en: 'A user compared you to a free Excel sheet. It hurts because it\'s partly true.' },
    fx: { motivation: -2 },
  },
  {
    id: 'feature_wave',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Пять юзеров просят одно и то же', en: 'Five users ask for the same thing' },
    text: { ru: 'Когда пятеро просят одно — это не фича-реквест, это дорожная карта.', en: 'When five people ask for the same thing, it\'s not a request — it\'s a roadmap.' },
    fx: { pmfBonus: 0.03, motivation: 2 },
  },
  {
    id: 'churn_survey',
    cat: 'users', char: 'churn_demon',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.paid >= 3,
    title: { ru: 'Узнал, почему уходят', en: 'You learned why they leave' },
    text: { ru: 'Разослал опрос ушедшим. Ответил один, но честно. Теперь ты знаешь.', en: 'Surveyed churned users. One replied, but honestly. Now you know.' },
    fx: { quality: 0.03 },
  },
  {
    id: 'user_hug',
    cat: 'users', char: 'paladin_fan',
    stageW: { garage: 1, traction: 1 },
    requires: (s) => s.paid >= 1,
    title: { ru: 'Юзер предложил помощь', en: 'A user offered to help' },
    text: { ru: '«Могу написать пару постов про вас, мне не сложно». Комьюнити — суперсила инди.', en: '"I can write a couple of posts about you, no big deal." Community is the indie superpower.' },
    fx: { audience: 50, motivation: 3 },
  },
  {
    id: 'elf_redesign_offer',
    cat: 'users', char: 'elf_designer',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.landing > 0 && s.landing < 0.8,
    title: { ru: 'Эльфийка предлагает редизайн', en: 'The elf offers a redesign' },
    text: { ru: '«Твой лендинг выглядит как таверна после драки. $400 — и будет эльфийский сад».', en: '"Your landing looks like a tavern after a brawl. $400 and it\'ll be an elven garden."' },
    choices: [
      { label: { ru: 'Заплатить $400', en: 'Pay $400' }, fx: { money: -400, landing: 0.2 } },
      { label: { ru: 'Сам сделаю', en: 'I\'ll do it myself' }, fx: {} },
    ],
  },
  {
    id: 'server_bill_shock',
    cat: 'money', char: 'gnome_devops',
    stageW: { garage: 1, traction: 2 },
    requires: (s) => s.deployed,
    title: { ru: 'Счёт за инфру удивил', en: 'A surprising infra bill' },
    text: { ru: 'Забытый тестовый воркер месяц крутился в проде. Гном ничего не заметил (пил пиво).', en: 'A forgotten test worker ran in prod for a month. The dwarf noticed nothing (beer).' },
    fx: { money: -120 },
  },
  {
    id: 'first_fan_art',
    cat: 'social', char: 'paladin_fan',
    stageW: { garage: 0, traction: 2 },
    requires: (s) => s.audience >= 200,
    title: { ru: 'Фан-арт твоего логотипа', en: 'Fan art of your logo' },
    text: { ru: 'Кто-то нарисовал твой логотип в стиле аниме. Это странно. И почётно.', en: 'Someone drew your logo in anime style. It\'s weird. And an honor.' },
    fx: { motivation: 5, audience: 30 },
  },
]
